### ISSUE TITLE
How can I troubleshoot 'Potentially Out of Sync' Message? [Help Wanted]

### ISSUE THREAD

**Issue by TimelyLog** [standardnotes/forum#1383]
**Describe the issue**
I use Standardnotes Web in Firefox and on three Android devices. On all my devices, I get the warning 'Potentially Out of Sync'. I tried signing out in the android app and in the web version (and cleared all website data) but the warning reappears in both instances.
Synchronization seems to work fine though. Any changes I make to my notes quickly I appear on all my devices and there seem to be no conflicting notes.

I would like to make sure that my notes actually sync properly, is there any way to troubleshoot this?

**Web:**
 - OS: Linux Mint 20.2
 - Browser: Firefox 90.0
 - Standard Notes Web version 3.8.18

**Smartphone:**
 - Device: Google Pixel 5
 - OS: Android 11
 - Standard Notes Android App Version 3.6.22

**Additional context**
I am subscribed standard notes extended and use themes/have some editors and components installed. Disabling the themes does not help

**Comment by mobitar** [comment]
Hey @TimelyLog, we've uncovered the cause of this issue for a small subset of users, and should have a fix out this week. We'll update this thread when that's ready.

**Comment by mobitar** [comment]
This issue should now be fixed. Please hit Refresh in the lower right corner of your web/desktop app to verify. On mobile, quit and restart the app.

**Comment by TimelyLog** [comment]
Unfortunately the issue persists for me, hitting the refresh button the web version and singing out and in again does not help. Quitting the app does also not resolve the issue.

**Comment by mobitar** [comment]
Hmm, can you email me your account email address in that case? Email is in bio.

**Comment by TimelyLog** [comment]
Sent you an email.
