### ISSUE TITLE
Default nested tags behavior

### ISSUE THREAD

**Issue by maiertech** [standardnotes/forum#1558]
**Describe the bug**

I am using native tags in the Mac desktop app. When I am in what looks like a folder defined by a nested tag, e.g. `coding/node`, and create a new note, it receives the following 2 tags:

- `coding`
- `coding/node`

![multiple-tags](https://user-images.githubusercontent.com/1482402/157763181-f6ea798d-b5e4-44aa-9711-eddf0454f9c7.png)

I then manually remove tag `coding`, because my intention was to put my note in folder `coding/note`.

![remove-tag](https://user-images.githubusercontent.com/1482402/157763488-5550d311-49ac-4fff-808c-f1474de03607.png)

**To Reproduce**

Just create nested tags as describe above.

**Expected behavior**

Since the tags are displayed as if they were folders, I would expect my note to receive only one tag, `coding/note` in above example.

I am fully aware that this behavior might be intended because notes can have multiple tags and a nested tag is just another tag with a special string format. But because the tag is nested and displayed as if it was a folder, I would expect it to behave more like a folder.

It still makes sense to allow multiple nested tags, e.g. `coding/node` and `project/2022/node` but I don't think these two nested tags should trigger additional tags `coding`, `project` and `project/2022`. Because the deeper the nested hierarchy gets, the more tags along the hierarchy are added.

In my example, if my note received only tag `coding/node` and I wanted it to have the `coding` tag, too, I could still add it manually, but I don't think it should be added by default.

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Version 3.13.0

**Comment by stefan-yas** [comment]
Right now that's the default behavior as we believe that most users would like to have an overview of all notes that are inside a specific folder in notes view, when they'd have a folder selected.

So, if for example, you'd have a note inside a nested tag "Thoughts", inside of a folder named "Miscellaneous", then your note would have both "Thoughts" as a tag, as well as "Miscellaneous/Thoughts", for convenience.

There isn't a workaround for this as it's the default behavior, so you'd have to manually remove the "Miscellaneous/Thoughts" tag from the note, if you'd like it to only appear in the "Thoughts" folder.

We've had one other similar report of this, but we might consider changing this logic if more users think this is not the best behavior.

**Comment by maiertech** [comment]
Fair enough.

**Comment by sebastianjacobs** [comment]
I am also not happy with this default behavior and I hope there will be an option soon to disable this.

**Comment by atmoio** [comment]
There will be an option to disable this in the next update 👍 You can control the preference on web/desktop, and the preference will sync to mobile and all your other devices.

**Comment by Regina3000** [comment]
Hmmm, I'm on 3.14.1, but I don't see a way to disable this. Where might I find this option?

Edit:  I'm on Windows.

Edit 2:  Found it. It's in General settings, in case anyone else has problems finding it.

**Comment by maiertech** [comment]
This option is broken on macOS v3.14.1. Might have been temporarily removed.

**Comment by adrihut** [comment]
Working fine on macOS on my end, for both full-path and singular tagging. Have you checked if your preferred option is toggled in **Preferences**?

![image](https://user-images.githubusercontent.com/91064300/162823749-0fdc1115-8aaf-402a-9044-1597d7832368.png)

**Comment by atmoio** [comment]
There is a known issue where this preference does not apply for notes created from within a subtag. However this is already fixed and pending deployment.

**Comment by Regina3000** [comment]
@moughxyz , do you know when this deployment will happen? I am still on 3.14.1 and still have this issue.

**Comment by atmoio** [comment]
Next release is in beta now: https://github.com/standardnotes/desktop/releases
