### ISSUE TITLE
[Android] Automatic theme seletion based on system doesn't seem to work

### ISSUE THREAD

**Issue by mystic-githuber** [standardnotes/forum#2229]
Automatic theme seletion based on system doesn't seem to work for me on my android device. My light theme loads automatically, I don't have more than one phone to test this out on other android phones.

The desktop version seems to be doing its job well for me.

**Comment by thethomasboyer** [comment]
Automatic theme switching does not seem to work for me either. The app seems to just switch to whatever is the selected light theme, even when my phone is in dark mode.

---
v3.44.3 (3002281), Android 13, One UI 5.0

**Comment by effieeee** [comment]
Hi all, while I haven't been able to reproduce this on my end just yet, I have been taking note of multiple reports of this, so we'll still try to look into it further 🙏

**Comment by julianfairfax** [comment]
Thank you! Can confirm this is an issue and hope to see a fix.

**Comment by opus-tango** [comment]
I am getting the same issue on Android, but also on Firefox on windows. The dark theme resets to light theme despite my Firefox theme being set to dark

**Comment by effieeee** [comment]
We've pushed a fix for this on v3.45.4, how is it on your end so far? @mystic-githuber

**Comment by julianfairfax** [comment]
> We've pushed a fix for this on v3.45.4, how is it on your end so far? @mystic-githuber

Works for me!

**Comment by opus-tango** [comment]
> We've pushed a fix for this on v3.45.4, how is it on your end so far? @mystic-githuber

I am still experiencing the problem on the webapp v3.90.10 using Firefox v106.0.3 on Windows 10
as well as on the android app v3.45.4 using a Google Pixel 4a running android 13 build TP1A.221005.002

**Comment by mystic-githuber** [comment]
@effieeee 
It seems to be working now. Should I close down the issue?

**Comment by effieeee** [comment]
Hmm, not just yet, @GShadow5 can I ask you to confirm if it still occurs as described on your end, even after clearing the app data on [Android](https://docs.standardnotes.com/troubleshooting/reset-apps/#android)?

**Comment by opus-tango** [comment]
@effieeee Yes, it is still occurring, I cleared data and cache, and I also tried uninstalling and reinstalled, but neither of those seems to have fixed it.

**Comment by effieeee** [comment]
@GShadow5 I see, I'll still be closing this issue for now since it seems to have been resolved for most users, but can I ask you to send us a message at help@standardnotes.com using your Standard Notes help account email? I'll help you troubleshoot this further from there 🙏

**Comment by karan** [comment]
This is definitely still happening.

V3.46.22

Every time I start the app I get a prompt asking me to keep the current theme or switch to system default

**Comment by effieeee** [comment]
Hi @karan, sorry to hear that it's still happening for you as well. Can I also ask you to send us a message at [help@standardnotes.com](mailto:help@standardnotes.com) using your Standard Notes help account email?

**Comment by karan** [comment]
As an update for the community - this has still not been investigated or fixed by SN. I did some troubleshooting with @effieeee but it didn't really lead to any resolution.
