### ISSUE TITLE
FileSafe extension corrupted after upgrade, Dark Theme bug

### ISSUE THREAD

**Issue by timetoseek** [standardnotes/forum#2281]
After upgrading the Windows Desktop version to 3.23.292, the FileSafe extension was apparently corrupted during the update.  However, with the Dark theme, the error message is not visible, only possible to view when selecting the text below "FileSafe", as in the screen print below:

![FileSafe_error](https://user-images.githubusercontent.com/26972658/201456789-f73ab80f-5cab-4691-b937-bbb4e930eb26.jpg)

**Comment by timetoseek** [comment]
Update: I uninstalled FileSafe as per instructions, but the option to re-install FileSafe is missing.

**Comment by effieeee** [comment]
Hi @timetoseek, please try these instructions to reinstall FileSafe:

1. Open Preferences > General > Advanced Settings
2. Scroll to the bottom, then copy and paste this link into the install box: https://extensions.standardnotes.org/repos/legacy/filesafe
3. Proceed through installation steps.

**Comment by timetoseek** [comment]
> 1. Open Preferences > General > Advanced Settings
> 2. Scroll to the bottom, then copy and paste this link into the install box: https://extensions.standardnotes.org/repos/legacy/filesafe
> 3. Proceed through installation steps.

Thank you, I followed the steps above, but unfortunately FileSafe is no longer visible as an option on the bottom of the note; FileSafe is no longer visible after uninstalling/reinstalling...

**Comment by timetoseek** [comment]
@effieeee I am able to view FileSafe through its tool icon via Alternative Rich Text note type  https://github.com/standardnotes/forum/issues/2269#issuecomment-1305784326.
However, I only use Plain Text note types and unfortunately after reinstall, FileSafe is not a visible menu option anywhere on the screen when using Plain Text note types. FileSafe used to be on the bottom of the page of Plain Text Notes, until corrupted by the most recent update ([@standardnotes/desktop@3.23.292](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.23.292))

**Comment by effieeee** [comment]
Hmm, do you mean that the FileSafe extension still doesn’t appear at the bottom where it used to be, or it’s there, but you still see the same error as in your first screenshot?

Is this still the case even after you’ve reinstalled the extension with the procedure above, then sign out and sign back into your account?

**Comment by timetoseek** [comment]
@effieeee  the issue has been resolved-- the final step to reactivate FileSafe is to toggle the "On" switch in the Quick Settings Menu, as per attached screen print.  Thank you for your help. I will close this issue.
![FileSafe_working](https://user-images.githubusercontent.com/26972658/201988501-f6b69e3a-6aaf-4034-b958-f801ba6909a0.jpg)

**Comment by xanoni** [comment]
I was able to reinstall FileSafe and toggled it "on" in the quick settings, but FileSafe still won't download/decrypt my attachments.

See https://github.com/standardnotes/forum/issues/1202#issuecomment-1381285698

Any ideas?

**Comment by timetoseek** [comment]
@xanoni 
> I was able to reinstall FileSafe and toggled it "on" in the quick settings, but FileSafe still won't download/decrypt my attachments.

Yes, I had the same situation, so the only to resolve was to un-install and re-install FileSafe in the Standard Notes desktop app.  Actually, I've had to do this from time to time, depending on if the latest release happens to corrupt the FileSafe integration.

If you are using the AWS integration, as I was, then also must delete the AWS FileSafe integration in Standard Notes, then add back AWS integration using this process again: (and be sure to use the same Access Key ID and Secret Key as when you originally installed the AWS integration) 
[FileSafe AWS Integration](/standardnotes/docs/wiki/How-to-configure-Amazon-S3-with-Standard-Notes-FileSafe)

**Comment by RohsCE** [comment]
> I was able to reinstall FileSafe and toggled it "on" in the quick settings, but FileSafe still won't download/decrypt my attachments.
> 
> See [#1202 (comment)](https://github.com/standardnotes/forum/issues/1202#issuecomment-1381285698)
> 
> Any ideas?

Just some more information if needed for others;
I remember when I was struggling with this, be sure (as the comments above suggest) that FileSafe was enabled via that toggle. Then, know the "FileSafe" button / toolbar at the bottom of the screen in a note does nothing anymore, IIRC. So ignore that, now you'll have to use the right editor. It's called [Alternative Rich Text](https://github.com/standardnotes/plugins). Then you can make a new note using that editor and click the ["FileSafe" button](https://imgur.com/j1wGAS4). It should [bring up a menu](https://imgur.com/PeI1zK7) where you can access the important stuff like uploading and decrypting.
I had a folder that I had saved, a bunch of encrypted files from the extension on my computer. In order to decrypt the files using FS, I uploaded those files to a google drive account, and made sure it was the same one FS was connected to (place it in the folder FS creates). If you connect it to the right folder, FS will recognise those files in that menu you brought up, and you should be able to decrypt them.
I should also add that, using the link provided in "Alternative Rich Text" - I was unable to get both alternative rich text and filesafe working. It was only when I used a SN backup that contained the information of both extensions, was I able to get it working in order to decrypt files.
