### ISSUE TITLE
"Moments" Labs Feature refuses to disable

### ISSUE THREAD

**Issue by NamesNetworkNic** [standardnotes/forum#2361]
The title makes the issue fairly self explainitory so I'm not going to make a lengthy write up about this.

Here's a screen recording of the issue:

https://user-images.githubusercontent.com/68761174/209543553-6a67c81a-3f75-4514-ab50-5069df68d829.mp4

I've been trying to turn it off for the last ten minutes.

Not to be rude, it's an interesting feature, I just really hate having my photo taken without my consent, so the fact that I can't turn this off is really bothering me.

Sorry for being unprofessional about this I'm just really tired.

xo Nicolete

**Comment by NamesNetworkNic** [comment]
I'd also like to note that the app softlocks on opening if I disable or deny the camera permission (it requires I reauthenicate to unlock the app and when I do either asks again or locks again depending on if I denied or disabled the permission).

**Comment by effieeee** [comment]
Hi @NamesNetworkNic, no worries, and sorry about the issue you're encountering. Can I first ask you to try clearing the app data so the app starts over from a fresh session? You may find some instructions for Android in [this link](https://docs.standardnotes.com/troubleshooting/reset-apps/#android).

**Comment by atmoio** [comment]
This issue has been fixed and an update has been pushed out. Hoping to fast-track it through Apple's review process.

**Comment by NamesNetworkNic** [comment]
Issue is NOT fixed after the new update.

I have deleted my storage and cache, re-signed in to my account and it initially appeared to be fixed, but after setting my biometric lock from requiring biometrics on quit to immediately the issue insantly reappeared, and persists after updating.

Screen recording as proof:


https://user-images.githubusercontent.com/68761174/209913786-5cb495ff-344f-4c2c-b273-426e8d06ce65.mp4

xo Nicolete

Also thank you effieeee for that link, I would not have figured out how to do that on my own.

**Comment by effieeee** [comment]
Hi @NamesNetworkNic, is this still the case even after clearing the app data on v3.130.2? Will ping Mo about it as well if it persists  even after clearing the app data

**Comment by NamesNetworkNic** [comment]
I've now cleared app data after updating and the issue is resolved (yaaay), sorry to keep you waiting.

Thank you all for your hard work making my favourite notes app, and I'm sorry about my unprofessionalism earlier.

xo Nicolete
