### ISSUE TITLE
App does not work after updating to 17.4

### ISSUE THREAD

**Issue by jacopo-j** [standardnotes/forum#3507]
**Describe the bug**
After updating to iOS 17.4, the Standard Notes app does not work and remains on the "Loading" screen indefinitely, as shown in the screenshot below.

**To Reproduce**
1. Update to iOS 17.4
2. Open the Standard Notes app

**Expected behavior**
The app opens and loads its content.

**Screenshots**
![IMG_4983](https://github.com/standardnotes/forum/assets/9914547/f4f8927d-9a9b-4b12-8919-d64d3ff02a54)

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 17.4
 - Version: 3.191.5

**Comment by gdcmarinho** [comment]
Sorry to ask. But this always needs to be done. Did you tried to uninstall and install the app again? Or restart the device?

**Comment by jacopo-j** [comment]
After deleting and reinstalling the app, I cannot even log back in. The app gets stuck at the following screen after entering the MFA code:
![IMG_4984](https://github.com/standardnotes/forum/assets/9914547/f48ed7ca-585a-4fea-94f2-ba9dcd0fc90e)

**Comment by fad1** [comment]
I have the same issue. using iOS 14.7. I verified that Lockdown mode is disabled.

This happens on an iPhone SE 2020 in my case

**Comment by bobleeSwagger2** [comment]
I am experiencing the same problem today. This needs attention ASAP 

details-
iOS 17.4
iPhone 14 Pro
App version 3.191.15

**Comment by rouspreda** [comment]
Also having the same issue:
- iPhone SE 2nd Gen
- iOS 17.4
- iPad 6th Gen
- iPadOS 17.4
- Standard Notes version 3.191.17

I've uninstalled the app, re-installed the app, even did a force restart of my devices. I log in, then it asks me to log in again. Then again, then again, etc. Standard Notes was working before the iOS/iPadOS 17.4 upgrade.

**Comment by alfism** [comment]
Similar thing happening on iPad after upgrade to 17.4.  It asks for login email and password, then my 2FA code, then a window pops up saying "Your session has been successfully restored.", but that is almost immediately covered up by another login window.  App version 3.191.17.

**Comment by gdcmarinho** [comment]
Try to send an e-mail to **help@standardnotes.com**.

**Comment by effieeee** [comment]
Hi all, for login and authentication issues without lockdown mode, most of these should be addressed in the update to v3.191.18, so please update the app to this version 🙏

We're also aware that the app is unable to login and authenticate on iOS 17.4 with lockdown mode at the moment, even when the app is added as an exception on lockdown mode, so this is something we're still looking into.

**Comment by fad1** [comment]
> Hi all, for login and authentication issues without lockdown mode, most of these should be addressed in the update to v3.191.18, so please update the app to this version 🙏
> 
> We're also aware that the app is unable to login and authenticate on iOS 17.4 with lockdown mode at the moment, even when the app is added as an exception on lockdown mode, so this is something we're still looking into.

I just retried deleting the app and reinstalling the latest. Still have the same issue. App stuck on sign in.

**Comment by rouspreda** [comment]
> Hi all, for login and authentication issues without lockdown mode, most of these should be addressed in the update to v3.191.18, so please update the app to this version 🙏
> 
> We're also aware that the app is unable to login and authenticate on iOS 17.4 with lockdown mode at the moment, even when the app is added as an exception on lockdown mode, so this is something we're still looking into.

Both my iPhone SE 2nd Gen & iPad 6th Gen are working w/ the latest 3.191.18 update.

**Comment by fad1** [comment]
The issue occurs with lockdown mode enabled, even if it is didsbled for standard mode. Issue disappears when lockdown mode is completely disabled. Please fix.

**Comment by postprivee** [comment]
ios17.4
webapp/pwa also not working when lockdown mode is enabled. disabling lockdown mode for (app.)standardnotes.com doesnt make any difference.

**Comment by jojopinkman1** [comment]
This may be a system bug. If your previous system version does not have this problem, it is recommended that you use [iOS system repair](https://www.joyoshare.com/ultfix/) tool to downgrade to the previous version or upgrade to the beta version. System downgrade will cause data loss, please back up your data in advance.

**Comment by alex17pat** [comment]
There are several reasons why your iPhone apps might not be updating, but don't worry, there are also ways to fix it! Here are some steps you can try:-
**1. Internet Connection:-** Apps need a stable internet connection (Wi-Fi or cellular data) to update. Make sure you're connected and that the signal is strong.
**2. App Store:-** Open the App Store app and try again. Sometimes a simple restart of the app can resolve the issue.
**3. Automatic Updates:-** Ensure automatic updates are enabled in Settings > App Store. This way, updates will download and install automatically whenever they become available.
**4. Log Out and In:-** Try logging out of your Apple ID in the App Store (Settings > App Store > Apple ID) and then logging back in. This can refresh your connection.
**5. Valid Payment Method:-** Verify you have a valid payment method associated with your Apple ID. Free apps won't require a payment method, but some updates might require in-app purchases.
More details assistance below.
https://thegeekpage.com/iphone-apps-not-updating-here-is-the-fix/
