### ISSUE TITLE
Folders extension - no folders / views displayed anymore

### ISSUE THREAD

**Issue by agba55** [standardnotes/forum#450]
Somehow the folders extension is no longer displaying any folders / tags / nested tags. It's a complete blank space (see screenshot).

![hmmm](https://user-images.githubusercontent.com/47297127/52183152-4808e200-2805-11e9-90c5-a2f426028a61.JPG)

Here's what happened:
I had the folders extension installed and activated
Been playing around with views + smart tags
I started to rename the 'standard' view "all notes" "trash" and "archived" to "1 all notes", "3 Archived" and "4 Trash" to do some ordering of the existing views. 
I saw that there was a second set of All notes Trash Archived re-appearing (above the 1 All notes, 3 Archived etc). 
After refreshing , the side bar with tags is empty.

Deactivating the folders extensions causes the side bar to re-appear. I also see the tags i re-named, plus the ones you'd see by default (i.e. 2 sets of the same tags). However, i can no longer delete the tags i renamed.
![hmmm2](https://user-images.githubusercontent.com/47297127/52183216-180e0e80-2806-11e9-96a7-848a32b21976.JPG)

**Comment by agba55** [comment]
i just successfully replicated the behavior in the demo environment: 

1. With Folders enabled
2. Rename the standard folders
3. Deactivate folders
4. Reactive folders
5. Sidebar is empty

**Comment by atmoio** [comment]
Good catch! I'm able to replicate this. Will have it fixed soon.

**Comment by atmoio** [comment]
Should be fixed in Folders 1.2.5. On web, clear your cache if you don't see the fix right away. On Desktop, use the Extensions menu to find Folders and choose the Update option.

**Comment by karan** [comment]
This issue still persists:

- Activate Folders
- Sidebar empty
- Deactivate folder
- Sidebar fine

Tried logging out and back in, and I can consistently repro this.

**Comment by JaspalSuri** [comment]
I'm sorry to hear that you're experiencing issues with the Folders Extension. :(

What OS are you using, and are you using the desktop or web app? Once I have those details, I'll have someone look into it.

**Comment by karan** [comment]
I'm on Mac using the web app.

**Comment by JaspalSuri** [comment]
What browser are you using? I currently can't reproduce this issue on either Firefox or Chrome.

**Comment by JaspalSuri** [comment]
Thank you for that! I'm afraid that I still wasn't able to reproduce the issue. Since you've tried several things and were still able to reproduce the issue, I would recommend that you try clearing your browser's cache.

That said, I'll will forward this over to the team to look into! Please consider using the [desktop app](https://standardnotes.org/download) in the meantime, if possible.

**Comment by karan** [comment]
Okay I left it disabled overnight, and tried re-activated it now and seems fine. I can see the sidebar again.

Will report back if that changes.

**Comment by JaspalSuri** [comment]
> Will report back if that changes.

Thank you! I'm glad that it's currently working! 🤞

**Comment by karan** [comment]
Hi - I'm seeing this again. Seems like it only temporarily helps to disable it and re-enable it.

<img width="295" alt="Screen Shot 2020-06-18 at 8 36 20 PM" src="https://user-images.githubusercontent.com/3261985/85094402-92dd8c80-b1a3-11ea-8204-e87f96a64065.png">

**Comment by JaspalSuri** [comment]
Hi, can you deactivate it to see if you have any duplicate or conflicting tags and try to delete those?

Also, what does the console say? Please press `cmd+shift+I` to access the developer tools and then switch to the `console` tab. Thanks so much in advance!

**Comment by karan** [comment]
So if I force refresh the page and see the following:

![image](https://user-images.githubusercontent.com/3261985/85177820-c666f800-b231-11ea-8cb4-3dce14cb110a.png)

Then within a second, it's all blank again.

There's no duplicate tags.

Here's the console output:

![image](https://user-images.githubusercontent.com/3261985/85177887-f0201f00-b231-11ea-9c91-21ce0e45d81d.png)

**Comment by JaspalSuri** [comment]
Hi Karan,

Thanks for the console output! Can you click on the small triangle on the left of the red line to expand what it says, blur out any details, and then send a screenshot of that? I apologize for not considering this in advance. 

Have you tried using the desktop app in the meantime?

**Comment by karan** [comment]
It's a long one but 
![image](https://user-images.githubusercontent.com/3261985/85190073-7d329a80-b269-11ea-835e-abce26f4f741.png)

I have not used the desktop app, I'm in no rush.

**Comment by JaspalSuri** [comment]
Thanks for the screenshot! I'll add it to our report.
