### ISSUE TITLE
[Bug] Advanced Markdown Editor on Android

### ISSUE THREAD

**Issue by ghost** [standardnotes/forum#528]
I really like this extension, but on Android it does not work at all. Every time I insert a space or move the cursor via the touch screen, text already in the note is being duplicated. It is also not possible to select text.

**Comment by mobitar** [comment]
Hmm this was an issue that was fixed several months ago. Is it possible you're running a cached version? Also, what version of the app are you using, and what version of Android?

**Comment by Garwyx** [comment]
App version is 3.0.5 and Android version 9 (Samsung Galaxy S9, it doesn't say much more than that, but it is the latest).

I logged in into the app again, and the problem persists.

**Comment by mobitar** [comment]
Can you go into your Android Settings > Storage > S. Notes > Clear Cache, then try launching the app again and seeing if the issue persists?

**Comment by Garwyx** [comment]
Clearing the cache did not solve it, but it works much better after rebooting and reinstalling. Thanks!

The only quirk that is still apparent is that pressing enter move the cursor to the beginning of the line and moves the line down, rather than inserting a new line below (cf. vim, it does Shift-O rather than O).

**Comment by mobitar** [comment]
Any chance you can capture a screen recording of that happening?

**Comment by Garwyx** [comment]
Sorry for taking so long, but here is a screen capture.

https://youtu.be/xZN4f8NecaE

Typing is alright most of the time, but it seems when I insert a new line after typing a single word on a line, the line is inserted above.

**Comment by mobitar** [comment]
Thanks for the video. Although, I'm still having a hard time seeing what you mean. So when you press enter in the middle of a line, the expected behavior is that anything to the right of the cursor moves to the line below, and the cursor is now at the beginning of this new line. It appears this is the behavior from the video. Am I overlooking something?

**Comment by raoul-van-oosten** [comment]
I should have given a better explanation. In the video, the problem arises as 0:17. All enters before that work as they should. So it seems the problem only occurs when I press enter after entering a single word on a line, not when I split a line that has been created earlier.

**Comment by mobitar** [comment]
Oh I see, it inserts a newline above. Hmm. I'll have to look into this. Only on Android I'm assuming? This is going to be a tricky one to fix, given we don't have control over the inner rendering of the editor.

**Comment by raoul-van-oosten** [comment]
I only use Android, so no clue what happens on iPhones. It would be great if you could look into it, but to me it is only a minor nuisance, so I am happily using the extension anyway.

**Comment by mobitar** [comment]
Btw, this is the main open-source repository for the editor, which we integrate: https://github.com/Ionaru/easy-markdown-editor

So it may be this issue was fixed in there but we haven't pulled in the changes. If not, it may not be a bad idea to post this same issue there. There was previously an issue where spellcheck on Android would cause duplication, and it was fixed in this repo, and we pulled the changes. That issue may in fact be related to this one.

**Comment by DarkArc** [comment]
I think this is duplicated by:
https://github.com/standardnotes/forum/issues/712

**Comment by markgloshen** [comment]
> I think this is duplicated by:
> #712

I'm not sure how #712 is a duplicate of this.  This issue is about "text already in the note is being duplicated. It is also not possible to select text."

#712 is a different issue altogether, and is about the keyboard obstructing the end of a note, making it impossible to work with.

**Comment by DarkArc** [comment]
Yeah I'm not sure what my reasoning was as that was 6 months ago and I also stopped using standard notes.

**Comment by raoul-van-oosten** [comment]
I have also stopped using Standard Notes so I am no longer following this issue.
